apiVersion: v1
kind: Service
metadata:
  name: ai-proxy
  namespace: ai-proxy
  labels:
    app: ai-proxy
spec:
  type: NodePort
  selector:
    app: ai-proxy
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
