replicaCount: 2

image:
  repository: ai-proxy
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: ai-proxy.local

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
